// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"user_id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	IsPrivate   *bool            `json:"is_private"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type CollectionPin struct {
	ID           int64            `json:"id"`
	CollectionID int64            `json:"collection_id"`
	PinID        int64            `json:"pin_id"`
	AddedAt      pgtype.Timestamp `json:"added_at"`
}

type Pin struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"user_id"`
	Title       string           `json:"title"`
	Description *string          `json:"description"`
	ImageUrl    string           `json:"image_url"`
	SourceUrl   *string          `json:"source_url"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	Sid       string    `json:"sid"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
}

type User struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  []byte `json:"password"`
}
